#!/usr/bin/env python3
"""
protein_validate_fgfr2_III_candidate_selection_v2_6.py

Protein-aware QC of FGFR2 IIIb/IIIc candidates.

Core biological rule (v2.8 rewrite)
-----------------------------------
FGFR2 IIIb/IIIc is a mutually exclusive exon-choice event in the third Ig-like
domain (D3):

  * FGFR2 IIIb is generated by inclusion of the IIIb-specific exon (human exon 8).
    Human RefSeq transcript anchor: NM_022970.3 (protein NP_075259.4).
  * FGFR2 IIIc is generated by inclusion of the IIIc-specific exon (human exon 9).
    Human RefSeq transcript anchor: NM_000141.4 (protein NP_000132.3).

The biological role (IIIb vs IIIc) is therefore assigned from the exon/event
architecture (Step 4 isoform evidence), NOT from whichever human protein segment
gives the higher score. Protein comparison is used ONLY as QC / plausibility
validation. This script:

  * derives ``expected_isoform_final`` from event/role assignment,
  * extracts the candidate's IIIb/IIIc cassette segment (local alignment to the
    human reference segments),
  * computes BOUNDED identity and coverage against both human references,
  * reports which isoform the protein prefers (``protein_prefers``) and whether it
    agrees with the expected isoform,
  * NEVER swaps the biological role automatically,
  * flags systematic inversions (expected-IIIb prefers IIIc AND expected-IIIc
    prefers IIIb) for review,
  * runs a mandatory human reference self-control (pipeline stops on failure) and
    a close-primate control (critical warning on failure).

When no protein-validated candidate exists for a role, the previously selected row
is retained with the original (event-based) role label but explicitly marked as
protein-unvalidated / review-only. Use --drop_unvalidated_roles to omit such rows.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
from exondomaincompare.scientific import protein_lookup as PL  # noqa: E402

SCRIPT_NAME = "protein_validate_fgfr2_III_candidate_selection_v2_6.py"
SCRIPT_VERSION = "2.8.1_event_based_role_bounded_qc_primate_diag"

# Close primates used for the qualitative positive control + diagnostics.
CLOSE_PRIMATE_SPECIES = [
    "pan_troglodytes",
    "gorilla_gorilla_gorilla",
    "gorilla_gorilla",
    "pongo_abelii",
    "macaca_mulatta",
]


def _interval_len_nt(sig: str) -> int:
    """Parse a 'chrom:start-end:strand' signature into a 1-based inclusive length."""
    if not sig:
        return 0
    m = re.search(r":(\d+)-(\d+)", str(sig))
    if not m:
        return 0
    a, b = int(m.group(1)), int(m.group(2))
    return abs(b - a) + 1


def event_structure_status(direction_validation: str, alt_exon_count: str, slot_reason: str) -> str:
    """Classify how strongly the exon/event structure supports the assigned role."""
    dv = (direction_validation or "").lower()
    try:
        n_alt = int(float(alt_exon_count)) if str(alt_exon_count).strip() else 0
    except Exception:
        n_alt = 0
    reason = (slot_reason or "").lower()
    if "two_alternative_exons" not in reason and n_alt and n_alt != 1 and "mutual" not in reason:
        # slots without a clean mutually-exclusive 2-exon structure are ambiguous.
        return "ambiguous_exon_slot"
    if "provisional" in dv or "requires_sequence" in dv or "requires_domain" in dv:
        return "direction_provisional_order_rule"
    if "validated" in dv or "confirmed" in dv:
        return "supports_expected_isoform_validated"
    if not dv:
        return "direction_unknown"
    return "weak_or_unvalidated"


# ---------------------------------------------------------------------------
# Small IO helpers
# ---------------------------------------------------------------------------
def read_tsv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as h:
        return list(csv.DictReader(h, delimiter="\t"))


def write_tsv(rows: List[Dict[str, str]], path: Path, fieldnames: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as h:
        w = csv.DictWriter(h, fieldnames=fieldnames, delimiter="\t", extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in fieldnames})


def clean_id(x: str) -> str:
    x = str(x or "").strip()
    if not x:
        return ""
    for prefix in ("rna-", "cds-", "protein-", "transcript:", "protein:", "RefSeq:", "Genbank:", "NCBI:"):
        if x.startswith(prefix):
            x = x[len(prefix):]
    return x.split(".", 1)[0]


def get_any(row: Dict[str, str], names: Iterable[str], default: str = "") -> str:
    lower = {k.lower(): k for k in row}
    for n in names:
        if n in row:
            return row.get(n, default)
        if n.lower() in lower:
            return row.get(lower[n.lower()], default)
    return default


def as_float(x: str, default: float = 0.0) -> float:
    try:
        if x is None or str(x).strip() == "":
            return default
        return float(str(x))
    except Exception:
        return default


def as_int(x: str, default: int = 0) -> int:
    try:
        if x is None or str(x).strip() == "":
            return default
        return int(float(str(x)))
    except Exception:
        return default


def read_fasta_records(path: Path) -> List[Tuple[str, str]]:
    """Return list of (header, sequence) preserving full header line."""
    out: List[Tuple[str, str]] = []
    header: Optional[str] = None
    parts: List[str] = []
    with path.open("r", encoding="utf-8") as h:
        for line in h:
            line = line.rstrip("\n")
            if not line.strip():
                continue
            if line.startswith(">"):
                if header is not None:
                    out.append((header, "".join(parts).upper().replace("*", "")))
                header = line[1:].strip()
                parts = []
            else:
                parts.append(re.sub(r"[^A-Za-z*]", "", line))
        if header is not None:
            out.append((header, "".join(parts).upper().replace("*", "")))
    return out


def read_single_fasta_with_header(path: Path) -> Tuple[str, str]:
    recs = read_fasta_records(path)
    if not recs:
        raise ValueError(f"No sequence in FASTA: {path}")
    return recs[0]


def read_single_fasta(path: Path) -> str:
    return read_single_fasta_with_header(path)[1]


# ---------------------------------------------------------------------------
# Local alignment with bounded identity / coverage (Smith-Waterman + traceback)
# ---------------------------------------------------------------------------
@dataclass
class AlignMetrics:
    score: int = 0
    identity: float = 0.0           # matches / aligned columns, bounded [0,1]
    coverage_ref: float = 0.0       # aligned reference residues / reference length, [0,1]
    q_start: int = 0                # 1-based start on query (candidate protein)
    q_end: int = 0                  # 1-based end on query
    aln_len: int = 0
    n_match: int = 0


def smith_waterman_local(query: str, ref: str, match: int = 2, mismatch: int = -1, gap: int = -2) -> AlignMetrics:
    """Bounded local alignment. Returns identity and reference coverage in [0,1].

    identity     = matched columns / aligned columns
    coverage_ref = (aligned span on reference) / len(reference)
    The query span (q_start, q_end) localises the candidate's cassette segment.
    """
    q = (query or "").upper()
    t = (ref or "").upper()
    n, m = len(q), len(t)
    if n == 0 or m == 0:
        return AlignMetrics()
    H = [[0] * (m + 1) for _ in range(n + 1)]
    best = 0
    bi = bj = 0
    for i in range(1, n + 1):
        qi = q[i - 1]
        Hi = H[i]
        Hp = H[i - 1]
        for j in range(1, m + 1):
            s = match if qi == t[j - 1] else mismatch
            v = Hp[j - 1] + s
            d = Hp[j] + gap
            if d > v:
                v = d
            e = Hi[j - 1] + gap
            if e > v:
                v = e
            if v < 0:
                v = 0
            Hi[j] = v
            if v > best:
                best = v
                bi, bj = i, j
    if best == 0:
        return AlignMetrics()
    i, j = bi, bj
    q_end, t_end = i, j
    n_match = aln_len = 0
    while i > 0 and j > 0 and H[i][j] > 0:
        cur = H[i][j]
        diag = H[i - 1][j - 1] + (match if q[i - 1] == t[j - 1] else mismatch)
        if cur == diag:
            aln_len += 1
            if q[i - 1] == t[j - 1]:
                n_match += 1
            i -= 1
            j -= 1
        elif cur == H[i - 1][j] + gap:
            i -= 1
            aln_len += 1
        else:
            j -= 1
            aln_len += 1
    q_start, t_start = i + 1, j + 1
    identity = (n_match / aln_len) if aln_len else 0.0
    coverage_ref = ((t_end - t_start + 1) / m) if m else 0.0
    return AlignMetrics(
        score=best,
        identity=round(min(1.0, max(0.0, identity)), 6),
        coverage_ref=round(min(1.0, max(0.0, coverage_ref)), 6),
        q_start=q_start,
        q_end=q_end,
        aln_len=aln_len,
        n_match=n_match,
    )


# ---------------------------------------------------------------------------
# Legacy unbounded marker scores (kept only as secondary tie-breakers)
# ---------------------------------------------------------------------------
def sw_local_score(a: str, b: str, match: int = 2, mismatch: int = -1, gap: int = -2) -> int:
    a = (a or "").upper()
    b = (b or "").upper()
    if not a or not b:
        return 0
    if len(a) > len(b):
        a, b = b, a
    prev = [0] * (len(b) + 1)
    best = 0
    for ca in a:
        cur = [0]
        for j, cb in enumerate(b, 1):
            s = match if ca == cb else mismatch
            v = max(0, prev[j - 1] + s, prev[j] + gap, cur[j - 1] + gap)
            cur.append(v)
            if v > best:
                best = v
        prev = cur
    return best


def normalized_local_support(query_protein: str, ref_segment: str) -> float:
    if not query_protein or not ref_segment:
        return 0.0
    denom = max(1, sw_local_score(ref_segment, ref_segment))
    return sw_local_score(query_protein, ref_segment) / denom


def unique_kmer_support(query_protein: str, ref_segment: str, other_ref_segment: str, k: int = 8) -> float:
    q = (query_protein or "").upper()
    r = (ref_segment or "").upper()
    o = (other_ref_segment or "").upper()
    if not q or not r or len(r) < k:
        return 0.0
    ref_kmers = {r[i:i + k] for i in range(0, len(r) - k + 1)}
    other_kmers = {o[i:i + k] for i in range(0, max(0, len(o) - k + 1))}
    unique = sorted(x for x in ref_kmers if x not in other_kmers and 'X' not in x)
    if not unique:
        return 0.0
    return sum(1 for x in unique if x in q) / len(unique)


def marker_scores(query_protein: str, iiib_ref: str, iiic_ref: str) -> Tuple[float, float]:
    """Legacy unbounded marker scores. NOT used for the primary protein_prefers
    decision (kept only for backward-compatibility reporting and tie-breaks)."""
    mk_b = unique_kmer_support(query_protein, iiib_ref, iiic_ref, k=8)
    mk_c = unique_kmer_support(query_protein, iiic_ref, iiib_ref, k=8)
    sw_b = normalized_local_support(query_protein, iiib_ref)
    sw_c = normalized_local_support(query_protein, iiic_ref)
    return mk_b + 0.05 * sw_b, mk_c + 0.05 * sw_c


# ---------------------------------------------------------------------------
# Bounded protein-preference and segment-extraction decisions
# ---------------------------------------------------------------------------
@dataclass
class ProteinQC:
    has_seq: bool
    iiib_identity: float
    iiib_coverage: float
    iiic_identity: float
    iiic_coverage: float
    iiib_marker_score: float
    iiic_marker_score: float
    protein_prefers: str            # IIIb / IIIc / ambiguous / unresolved
    segment_extraction_method: str
    segment_extraction_confidence: str
    extracted_segment_start: int
    extracted_segment_end: int
    extracted_segment_length: int
    extracted_segment_sequence: str
    extracted_segment_warning: str


def evaluate_protein(seq: str, expected_final: str, iiib_ref: str, iiic_ref: str,
                     pref_margin: float, min_segment_cov: float) -> ProteinQC:
    if not seq:
        return ProteinQC(False, 0, 0, 0, 0, 0, 0, "unresolved", "unresolved",
                         "none", 0, 0, 0, "", "no_protein_sequence")
    mb = smith_waterman_local(seq, iiib_ref)
    mc = smith_waterman_local(seq, iiic_ref)
    mk_b, mk_c = marker_scores(seq, iiib_ref, iiic_ref)
    score_b = mb.identity * mb.coverage_ref
    score_c = mc.identity * mc.coverage_ref

    best_cov = max(mb.coverage_ref, mc.coverage_ref)
    warning = ""
    if best_cov < min_segment_cov:
        prefers = "unresolved"
        warning = f"both_reference_coverages_below_{min_segment_cov}"
    elif abs(score_b - score_c) < pref_margin:
        prefers = "ambiguous"
        warning = "identity_x_coverage_difference_below_margin"
        # break ties with discriminative markers if they clearly disagree.
        if mk_b - mk_c > 0.25:
            prefers = "IIIb"
            warning = "ambiguous_alignment_resolved_by_markers"
        elif mk_c - mk_b > 0.25:
            prefers = "IIIc"
            warning = "ambiguous_alignment_resolved_by_markers"
    elif score_b > score_c:
        prefers = "IIIb"
    else:
        prefers = "IIIc"

    # Segment extraction: use the EXPECTED isoform's local-alignment span as the
    # candidate cassette region (anchor_region_window). At Step 5b resolved
    # CDS->protein intervals are not yet available, so this is the best available
    # evidence and is capped at moderate confidence.
    exp = mb if expected_final == "IIIb" else mc
    if exp.coverage_ref < min_segment_cov and best_cov < min_segment_cov:
        method = "unresolved"
        conf = "none"
        seg_start = seg_end = seg_len = 0
        seg_seq = ""
        if not warning:
            warning = "no_reliable_segment_window"
    else:
        # If the expected reference barely aligns but the other one does, still
        # report the best-covering window but flag it.
        use = exp if exp.coverage_ref >= min_segment_cov else (mb if mb.coverage_ref >= mc.coverage_ref else mc)
        method = "anchor_region_window"
        seg_start = use.q_start
        seg_end = use.q_end
        seg_len = max(0, seg_end - seg_start + 1)
        seg_seq = seq[seg_start - 1:seg_end] if seg_start and seg_end else ""
        if use.coverage_ref >= 0.80 and use.identity >= 0.60:
            conf = "moderate"   # anchor window (not resolved CDS) -> capped at moderate
        elif use.coverage_ref >= 0.50:
            conf = "low"
        else:
            conf = "low"
            if not warning:
                warning = "low_reference_coverage_for_segment_window"

    return ProteinQC(
        has_seq=True,
        iiib_identity=mb.identity,
        iiib_coverage=mb.coverage_ref,
        iiic_identity=mc.identity,
        iiic_coverage=mc.coverage_ref,
        iiib_marker_score=round(mk_b, 6),
        iiic_marker_score=round(mk_c, 6),
        protein_prefers=prefers,
        segment_extraction_method=method,
        segment_extraction_confidence=conf,
        extracted_segment_start=seg_start,
        extracted_segment_end=seg_end,
        extracted_segment_length=seg_len,
        extracted_segment_sequence=seg_seq,
        extracted_segment_warning=warning,
    )


# ---------------------------------------------------------------------------
# Reference manifest
# ---------------------------------------------------------------------------
@dataclass
class RefEntry:
    isoform: str
    refseq_transcript: str
    refseq_protein: str
    reference_fasta: str
    expected_event: str
    notes: str
    fasta_header: str = ""
    sequence: str = ""


def load_reference_manifest(path: Path, repo_root: Path) -> Dict[str, RefEntry]:
    rows = read_tsv(path)
    out: Dict[str, RefEntry] = {}
    for r in rows:
        iso = (r.get("isoform") or "").strip()
        if iso not in {"IIIb", "IIIc"}:
            continue
        fa_rel = (r.get("reference_fasta") or "").strip()
        fa = Path(fa_rel)
        if not fa.is_absolute():
            fa = (repo_root / fa_rel)
        header = seq = ""
        if fa.exists():
            try:
                header, seq = read_single_fasta_with_header(fa)
            except Exception:
                header, seq = "", ""
        out[iso] = RefEntry(
            isoform=iso,
            refseq_transcript=(r.get("refseq_transcript") or "").strip(),
            refseq_protein=(r.get("refseq_protein") or "").strip(),
            reference_fasta=fa_rel,
            expected_event=(r.get("expected_event") or "").strip(),
            notes=(r.get("notes") or "").strip(),
            fasta_header=header,
            sequence=seq,
        )
    return out


def manifest_check(manifest: Dict[str, RefEntry], iiib_ref: str, iiic_ref: str) -> Tuple[List[Dict[str, str]], str]:
    """Validate the manifest against the actual reference FASTAs and against the
    scoring direction. Returns (rows, overall_status)."""
    rows: List[Dict[str, str]] = []
    overall_ok = True
    _seqs = {"IIIb": iiib_ref, "IIIc": iiic_ref}
    for iso in ("IIIb", "IIIc"):
        e = manifest.get(iso)
        warnings: List[str] = []
        status = "ok"
        if e is None:
            rows.append({
                "isoform": iso, "manifest_refseq_transcript": "", "manifest_refseq_protein": "",
                "reference_fasta": "", "fasta_header": "", "sequence_length_aa": "0",
                "sequence_first_20aa": "", "sequence_last_20aa": "",
                "manifest_check_status": "missing_manifest_row",
                "manifest_check_warning": f"no manifest row for {iso}",
            })
            overall_ok = False
            continue
        seq = e.sequence
        if not seq:
            status = "fasta_missing_or_empty"
            warnings.append(f"could not read reference FASTA {e.reference_fasta}")
            overall_ok = False
        # Header isoform label must agree with manifest isoform.
        header_l = e.fasta_header.lower()
        if "iiib" in header_l and "iiic" not in header_l:
            header_iso = "IIIb"
        elif "iiic" in header_l and "iiib" not in header_l:
            header_iso = "IIIc"
        else:
            header_iso = ""
        if header_iso and header_iso != iso:
            status = "header_isoform_mismatch"
            warnings.append(f"FASTA header labels {header_iso} but manifest says {iso}")
            overall_ok = False
        elif not header_iso:
            warnings.append("could not parse isoform label from FASTA header")
        rows.append({
            "isoform": iso,
            "manifest_refseq_transcript": e.refseq_transcript,
            "manifest_refseq_protein": e.refseq_protein,
            "reference_fasta": e.reference_fasta,
            "fasta_header": e.fasta_header,
            "sequence_length_aa": str(len(seq)),
            "sequence_first_20aa": seq[:20],
            "sequence_last_20aa": seq[-20:],
            "manifest_check_status": status,
            "manifest_check_warning": ";".join(warnings),
        })
    return rows, ("ok" if overall_ok else "fail")


# ---------------------------------------------------------------------------
# Protein lookup wrapper (shared logic with Step 6 export)
# ---------------------------------------------------------------------------
def protein_for_row(row: Dict[str, str], cache_index: "PL.ProteinCacheIndex",
                    protein_cache: Dict[str, "PL.ProteinLookupResult"], args: argparse.Namespace) -> "PL.ProteinLookupResult":
    translation = clean_id(get_any(row, ["translation_id_source", "protein_id", "translation_id"]))
    transcript = clean_id(get_any(row, ["transcript_id_source", "transcript_id"]))
    source_db = get_any(row, ["source_db", "source"])
    species_input = get_any(row, ["species_input"])
    species_canonical = get_any(row, ["species_canonical", "species"])
    expected_len = as_int(get_any(row, ["protein_length_aa"]), 0) or None
    key = "|".join([source_db, translation, transcript])
    if key in protein_cache:
        return protein_cache[key]
    res = PL.lookup_protein(
        cache_index,
        source_db=source_db,
        transcript_id=transcript,
        translation_id=translation,
        species_input=species_input,
        species_canonical=species_canonical,
        expected_length_aa=expected_len,
        allow_ensembl_rest=not args.no_ensembl_rest,
        ensembl_sleep=args.ensembl_sleep,
        ensembl_timeout=args.ensembl_timeout,
    )
    protein_cache[key] = res
    return res


def make_row_from_transcript_and_iso(tx: Dict[str, str], iso: Dict[str, str], selected_fields: List[str]) -> Dict[str, str]:
    r = {k: "" for k in selected_fields}
    for k, v in tx.items():
        if k in r:
            r[k] = v
    for k in ["species_input", "species_canonical", "source_db", "gene_symbol", "gene_id_internal",
              "internal_transcript_id", "transcript_id_source", "transcript_name", "protein_length_aa"]:
        if k in r and not r.get(k):
            r[k] = get_any(iso, [k])
    if "translation_id_source" in r and not r.get("translation_id_source"):
        r["translation_id_source"] = get_any(tx, ["translation_id_source"])
    if "iii_isoform_assignment" in r:
        r["iii_isoform_assignment"] = get_any(iso, ["iii_isoform_assignment", "isoform_class"])
    if "iii_isoform_confidence" in r:
        r["iii_isoform_confidence"] = get_any(iso, ["confidence", "iii_isoform_confidence"])
    if "iii_isoform_evidence" in r:
        r["iii_isoform_evidence"] = get_any(iso, ["evidence", "iii_isoform_evidence"])
    if "selection_mode" in r and not r.get("selection_mode"):
        r["selection_mode"] = "protein_sequence_validated_isoform_candidate"
    if "score" in r and not r.get("score"):
        r["score"] = get_any(iso, ["score_from_selection"], "0")
    return r




def id_key(row: Dict[str, str]) -> str:
    return clean_id(get_any(row, ["internal_transcript_id"])) or clean_id(get_any(row, ["transcript_id_source", "transcript_id"]))


def role_to_isoform(role: str) -> str:
    role = role or ""
    if "IIIb" in role:
        return "IIIb"
    if "IIIc" in role:
        return "IIIc"
    return ""


# ---------------------------------------------------------------------------
# Candidate ranking (role stays event-based; protein only ranks within a role)
# ---------------------------------------------------------------------------
_VALIDATION_RANK = {
    "protein_validated_expected_isoform": 5,
    "protein_supports_expected_isoform_below_strict_threshold": 4,
    "protein_ambiguous_inconclusive": 3,
    "transcript_level_evidence_only_protein_unavailable": 2,
    "unresolved_segment_extraction": 1,
    "protein_conflicts_expected_isoform": 0,
    "systematic_isoform_inversion_review": 0,
}
_CONF_RANK = {"high": 2, "medium": 1, "low": 0, "none": 0, "": 0}


def best_candidate(candidates: List[Dict[str, str]]) -> Optional[Dict[str, str]]:
    """Pick the representative candidate for an event-based role. Selection never
    changes the biological role; it only orders candidates within the role."""
    if not candidates:
        return None

    def key(c: Dict[str, str]) -> Tuple:
        return (
            _VALIDATION_RANK.get(c.get("validation_status", ""), 0),
            _CONF_RANK.get(c.get("iii_isoform_confidence", ""), 0),
            as_float(c.get("score")),
            as_int(c.get("protein_length_aa")),
            get_any(c, ["transcript_id_source"]),
        )
    return sorted(candidates, key=key, reverse=True)[0]


# ---------------------------------------------------------------------------
# Per-candidate validation status
# ---------------------------------------------------------------------------
def derive_validation_status(found: bool, qc: ProteinQC, expected_final: str,
                             strict_id: float, strict_cov: float) -> Tuple[str, str, str]:
    """Return (validation_status, suspected_issue, protein_qc_status)."""
    if not found:
        return ("transcript_level_evidence_only_protein_unavailable", "",
                "protein_unavailable")
    if qc.segment_extraction_method == "unresolved" or qc.protein_prefers == "unresolved":
        return ("unresolved_segment_extraction", "segment_extraction_failed",
                "segment_unresolved")
    prefers = qc.protein_prefers
    exp_id = qc.iiib_identity if expected_final == "IIIb" else qc.iiic_identity
    exp_cov = qc.iiib_coverage if expected_final == "IIIb" else qc.iiic_coverage
    if prefers == expected_final:
        if exp_id >= strict_id and exp_cov >= strict_cov:
            return ("protein_validated_expected_isoform", "", "protein_available")
        return ("protein_supports_expected_isoform_below_strict_threshold",
                "below_strict_identity_or_coverage", "protein_available")
    if prefers == "ambiguous":
        return ("protein_ambiguous_inconclusive", "low_protein_discrimination",
                "protein_available_low_discrimination")
    # prefers is the other concrete isoform -> conflict.
    return ("protein_conflicts_expected_isoform", "protein_conflicts_event_assignment",
            "protein_available")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def run(args: argparse.Namespace) -> Dict[str, object]:
    repo_root = Path(__file__).resolve().parent.parent
    selected = read_tsv(args.selected)
    transcripts = read_tsv(args.transcripts)
    iso_rows = read_tsv(args.isoform_evidence)
    iiib_header, iiib_ref = read_single_fasta_with_header(args.human_iiib_segment_fasta)
    iiic_header, iiic_ref = read_single_fasta_with_header(args.human_iiic_segment_fasta)

    outdir = args.outdir
    outdir.mkdir(parents=True, exist_ok=True)

    # --- Reference manifest + check (PART B) ------------------------------
    manifest: Dict[str, RefEntry] = {}
    manifest_rows: List[Dict[str, str]] = []
    manifest_status = "not_provided"
    if args.reference_manifest and Path(args.reference_manifest).exists():
        manifest = load_reference_manifest(Path(args.reference_manifest), repo_root)
        manifest_rows, manifest_status = manifest_check(manifest, iiib_ref, iiic_ref)
    write_tsv(
        manifest_rows,
        outdir / "fgfr2_III_reference_manifest_check.tsv",
        ["isoform", "manifest_refseq_transcript", "manifest_refseq_protein", "reference_fasta",
         "fasta_header", "sequence_length_aa", "sequence_first_20aa", "sequence_last_20aa",
         "manifest_check_status", "manifest_check_warning"],
    )

    selected_fields = list(selected[0].keys()) if selected else []
    required_min = [
        "species_input", "species_canonical", "source_db", "gene_symbol", "gene_id_internal",
        "selection_role", "selection_rank", "selection_mode", "overlapping_roles", "all_roles_for_transcript",
        "transcript_id_source", "internal_transcript_id", "transcript_name", "transcript_biotype",
        "translation_id_source", "protein_length_aa", "score", "has_translation",
        "iii_isoform_assignment", "iii_isoform_confidence", "iii_isoform_evidence", "final_selection_reason",
    ]
    for f in required_min:
        if f not in selected_fields:
            selected_fields.append(f)
    extra_fields = [
        "expected_isoform_from_event", "expected_isoform_from_role", "expected_isoform_final",
        "protein_prefers", "protein_qc_status", "validation_status", "suspected_issue",
        "protein_validation_is_decisive", "validation_warning", "primary_claim_eligible",
        "human_IIIb_identity", "human_IIIc_identity", "human_IIIb_coverage", "human_IIIc_coverage",
        "human_IIIb_marker_score", "human_IIIc_marker_score",
        "segment_extraction_method", "segment_extraction_confidence",
        "extracted_segment_start", "extracted_segment_end", "extracted_segment_length",
        "protein_sequence_status", "protein_lookup_method", "protein_lookup_confidence",
    ]
    for f in extra_fields:
        if f not in selected_fields:
            selected_fields.append(f)

    tx_by_source: Dict[Tuple[str, str], Dict[str, str]] = {}
    tx_by_internal: Dict[Tuple[str, str], Dict[str, str]] = {}
    for tx in transcripts:
        sp = get_any(tx, ["species_canonical", "species_input"])
        src = clean_id(get_any(tx, ["transcript_id_source", "transcript_id"]))
        internal = clean_id(get_any(tx, ["internal_transcript_id"]))
        if src:
            tx_by_source[(sp, src)] = tx
        if internal:
            tx_by_internal[(sp, internal)] = tx

    selected_by_species: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    for r in selected:
        sp = get_any(r, ["species_canonical", "species_input"])
        selected_by_species[sp].append(dict(r))

    selected_lookup: Dict[Tuple[str, str], Dict[str, str]] = {}
    for r in selected:
        sp = get_any(r, ["species_canonical", "species_input"])
        selected_lookup[(sp, id_key(r))] = dict(r)

    # Shared protein cache index (restricted to needed accessions for speed).
    wanted_acc = set()
    wanted_tx = set()
    for src in (iso_rows, transcripts, selected):
        for r in src:
            tid = clean_id(get_any(r, ["translation_id_source", "protein_id", "translation_id"]))
            tx = clean_id(get_any(r, ["transcript_id_source", "transcript_id"]))
            if tid:
                wanted_acc.add(tid)
            if tx:
                wanted_tx.add(tx)
    cache_index = PL.ProteinCacheIndex(args.cache, wanted_accessions=wanted_acc, wanted_transcripts=wanted_tx)
    protein_cache: Dict[str, PL.ProteinLookupResult] = {}

    scored_candidates: List[Dict[str, str]] = []
    by_species_role: Dict[Tuple[str, str], List[Dict[str, str]]] = defaultdict(list)

    for iso in iso_rows:
        assignment = get_any(iso, ["iii_isoform_assignment", "isoform_class"])
        confidence = get_any(iso, ["confidence", "iii_isoform_confidence"])
        if assignment not in {"IIIb", "IIIc"}:
            continue
        if confidence not in {"high", "medium"} and not args.include_low_confidence:
            continue
        sp = get_any(iso, ["species_canonical", "species_input"])
        src = clean_id(get_any(iso, ["transcript_id_source", "transcript_id"]))
        internal = clean_id(get_any(iso, ["internal_transcript_id"]))
        tx = tx_by_internal.get((sp, internal)) or tx_by_source.get((sp, src)) or {}
        base = selected_lookup.get((sp, internal), {}) or selected_lookup.get((sp, src), {})
        row = dict(base) if base else make_row_from_transcript_and_iso(tx, iso, selected_fields)
        row["iii_isoform_assignment"] = assignment
        row["iii_isoform_confidence"] = confidence
        row["iii_isoform_evidence"] = get_any(iso, ["evidence", "iii_isoform_evidence"])
        for k in ["species_input", "species_canonical", "source_db", "gene_id_internal",
                  "transcript_id_source", "internal_transcript_id", "transcript_name", "protein_length_aa"]:
            if not row.get(k):
                row[k] = get_any(tx, [k]) or get_any(iso, [k])
        if not row.get("translation_id_source"):
            row["translation_id_source"] = get_any(tx, ["translation_id_source"])
        if not row.get("has_translation"):
            row["has_translation"] = "1" if row.get("translation_id_source") or as_int(row.get("protein_length_aa")) > 0 else "0"

        # Expected isoform: PRIMARY = event assignment; role only as cross-check.
        expected_event = assignment
        expected_role = role_to_isoform(get_any(iso, ["selection_role"]) or get_any(row, ["selection_role"]))
        expected_final = expected_event or expected_role

        rec = protein_for_row(row, cache_index, protein_cache, args)
        seq = rec.sequence
        qc = evaluate_protein(seq, expected_final, iiib_ref, iiic_ref, args.pref_margin, args.min_segment_coverage)
        status, suspected, qc_status = derive_validation_status(
            rec.found, qc, expected_final, args.min_identity, args.min_coverage)

        warnings_for_row: List[str] = []
        if qc.extracted_segment_warning:
            warnings_for_row.append(qc.extracted_segment_warning)
        if rec.found and rec.protein_sequence_status == PL.STATUS_FOUND_CACHE_FALLBACK:
            warnings_for_row.append("protein_via_cache_fallback_inspect")
        if not rec.found:
            warnings_for_row.append(f"protein_unavailable:{rec.protein_sequence_status}")

        row.update({
            "species": sp,
            "role": expected_final,
            "selection_role": get_any(iso, ["selection_role"]) or get_any(row, ["selection_role"]),
            "transcript_id": clean_id(get_any(row, ["transcript_id_source", "transcript_id"])),
            "protein_id": rec.matched_accession or clean_id(get_any(row, ["translation_id_source", "protein_id"])),
            "source_db": get_any(row, ["source_db", "source"]),
            "expected_isoform_from_event": expected_event,
            "expected_isoform_from_role": expected_role,
            "expected_isoform_final": expected_final,
            "protein_sequence_status": rec.protein_sequence_status,
            "protein_lookup_method": rec.lookup_method,
            "protein_lookup_confidence": rec.lookup_confidence,
            "protein_length_aa_observed": str(rec.length_aa) if seq else "",
            "segment_extraction_method": qc.segment_extraction_method,
            "segment_extraction_confidence": qc.segment_extraction_confidence,
            "extracted_segment_start": str(qc.extracted_segment_start) if qc.has_seq else "",
            "extracted_segment_end": str(qc.extracted_segment_end) if qc.has_seq else "",
            "extracted_segment_length": str(qc.extracted_segment_length) if qc.has_seq else "",
            "extracted_segment_sequence": qc.extracted_segment_sequence,
            "human_IIIb_identity": f"{qc.iiib_identity:.4f}" if qc.has_seq else "",
            "human_IIIc_identity": f"{qc.iiic_identity:.4f}" if qc.has_seq else "",
            "human_IIIb_coverage": f"{qc.iiib_coverage:.4f}" if qc.has_seq else "",
            "human_IIIc_coverage": f"{qc.iiic_coverage:.4f}" if qc.has_seq else "",
            "human_IIIb_marker_score": f"{qc.iiib_marker_score:.4f}" if qc.has_seq else "",
            "human_IIIc_marker_score": f"{qc.iiic_marker_score:.4f}" if qc.has_seq else "",
            # legacy unbounded columns kept (do NOT use for final decisions).
            "human_IIIb_similarity_legacy_unbounded": f"{qc.iiib_marker_score:.4f}" if qc.has_seq else "",
            "human_IIIc_similarity_legacy_unbounded": f"{qc.iiic_marker_score:.4f}" if qc.has_seq else "",
            "protein_prefers": qc.protein_prefers,
            "protein_qc_status": qc_status,
            "validation_status": status,
            "suspected_issue": suspected,
            "protein_validation_is_decisive": "false",
            "validation_warning": ";".join(warnings_for_row),
            "protein_sequence_source": rec.lookup_method,
            "protein_sequence_detail": rec.detail,
        })
        # Event/exon-structure context captured from the isoform-evidence row so
        # downstream diagnostics can compare protein QC against event structure.
        _matched = get_any(iso, ["matched_alt_exons"])
        row.update({
            "candidate_exon_slot_id": get_any(iso, ["slot_id"]),
            "upstream_flanking_exon_id": get_any(iso, ["left_flank_sig"]),
            "downstream_flanking_exon_id": get_any(iso, ["right_flank_sig"]),
            "matched_alt_exons": _matched,
            "alt_exon_count_in_slot": get_any(iso, ["alt_exon_count_in_slot"]),
            "direction_validation_status": get_any(iso, ["direction_validation_status"]),
            "assignment_rule": get_any(iso, ["assignment_rule"]),
            "slot_confidence_reason": get_any(iso, ["slot_confidence_reason"]),
            "candidate_exon_length_nt": str(_interval_len_nt(_matched)),
            "candidate_cds_length_nt": str(_interval_len_nt(_matched)),
            "candidate_aa_length": str(_interval_len_nt(_matched) // 3) if _matched else "",
            "event_structure_status": event_structure_status(
                get_any(iso, ["direction_validation_status"]),
                get_any(iso, ["alt_exon_count_in_slot"]),
                get_any(iso, ["slot_confidence_reason"]),
            ),
        })
        scored_candidates.append(row)
        by_species_role[(sp, expected_final)].append(row)

    # --- Systematic inversion detection (PART E) --------------------------
    species_inversion: Dict[str, bool] = {}
    warnings: List[Dict[str, str]] = []
    for sp in sorted({s for (s, _r) in by_species_role}):
        b_rows = by_species_role.get((sp, "IIIb"), [])
        c_rows = by_species_role.get((sp, "IIIc"), [])
        b_best = best_candidate(b_rows)
        c_best = best_candidate(c_rows)
        b_pref = b_best.get("protein_prefers") if b_best else None
        c_pref = c_best.get("protein_prefers") if c_best else None
        inverted = (b_pref == "IIIc" and c_pref == "IIIb")
        species_inversion[sp] = inverted
        if inverted:
            for r in b_rows + c_rows:
                if r.get("validation_status") == "protein_conflicts_expected_isoform":
                    r["validation_status"] = "systematic_isoform_inversion_review"
                    r["suspected_issue"] = "reference_swapped_or_role_mapping_inverted_or_segment_extraction_wrong"
            warnings.append({
                "species": sp,
                "warning_type": "systematic_isoform_inversion",
                "severity": "critical",
                "affected_roles": "IIIb;IIIc",
                "description": ("Expected-IIIb candidate prefers human IIIc and expected-IIIc candidate prefers human IIIb. "
                                "References verified correct by self-control; most likely upstream exon/event role mapping is inverted for this species."),
                "recommended_action": "Review Step 4 exon/event assignment and transcript->protein mapping; do NOT auto-swap roles.",
            })
        else:
            # Per-role single conflicts (not full inversion) still get a warning.
            for role, rows in (("IIIb", b_rows), ("IIIc", c_rows)):
                best = best_candidate(rows)
                if best and best.get("validation_status") == "protein_conflicts_expected_isoform":
                    warnings.append({
                        "species": sp,
                        "warning_type": "protein_conflicts_event_assignment",
                        "severity": "warning",
                        "affected_roles": role,
                        "description": f"Expected {role} candidate's protein prefers {best.get('protein_prefers')}.",
                        "recommended_action": "Manual review; treat protein QC as non-decisive.",
                    })

    # --- Controls (PART B) ------------------------------------------------
    debug_controls: List[Dict[str, str]] = []
    control_status: Dict[str, str] = {}

    # (1) Reference self-control: each human reference must prefer itself. This
    #     validates that the references are NOT swapped and the scoring direction
    #     is correct. Failure => stop the pipeline.
    ref_ok = True
    for iso, refseq in (("IIIb", iiib_ref), ("IIIc", iiic_ref)):
        qc = evaluate_protein(refseq, iso, iiib_ref, iiic_ref, args.pref_margin, args.min_segment_coverage)
        ok = (qc.protein_prefers == iso)
        ref_ok = ref_ok and ok
        debug_controls.append({
            "control_type": "reference_self_control",
            "species": "homo_sapiens",
            "role": iso,
            "selection_role": f"FGFR2_{iso}_reference",
            "transcript_id": (manifest.get(iso).refseq_transcript if manifest.get(iso) else ""),
            "protein_id": (manifest.get(iso).refseq_protein if manifest.get(iso) else ""),
            "expected_isoform_from_event": iso,
            "expected_isoform_final": iso,
            "extracted_segment_start": str(qc.extracted_segment_start),
            "extracted_segment_end": str(qc.extracted_segment_end),
            "extracted_segment_length": str(qc.extracted_segment_length),
            "extracted_segment_sequence": qc.extracted_segment_sequence,
            "human_IIIb_reference_header": iiib_header,
            "human_IIIc_reference_header": iiic_header,
            "human_IIIb_reference_length": str(len(iiib_ref)),
            "human_IIIc_reference_length": str(len(iiic_ref)),
            "human_IIIb_identity": f"{qc.iiib_identity:.4f}",
            "human_IIIc_identity": f"{qc.iiic_identity:.4f}",
            "human_IIIb_coverage": f"{qc.iiib_coverage:.4f}",
            "human_IIIc_coverage": f"{qc.iiic_coverage:.4f}",
            "human_IIIb_marker_score": f"{qc.iiib_marker_score:.4f}",
            "human_IIIc_marker_score": f"{qc.iiic_marker_score:.4f}",
            "protein_prefers": qc.protein_prefers,
            "validation_status": "reference_control_passed" if ok else "reference_control_failed",
            "suspected_issue": "" if ok else "references_swapped_or_scoring_inverted",
        })
    control_status["reference_self_control"] = "pass" if ref_ok else "fail"

    # (1b) Human full-length protein control (deterministic, offline). Uses the
    #      curated human FGFR2-IIIb / FGFR2-IIIc full proteins so a real human
    #      positive control always runs even without network access. Failure here
    #      means references/scoring are wrong => stop the pipeline.
    human_ref_protein_ok = None
    human_ref_proteins = {
        "IIIb": args.human_iiib_protein_fasta,
        "IIIc": args.human_iiic_protein_fasta,
    }
    if all(p and Path(p).exists() for p in human_ref_proteins.values()):
        human_ref_protein_ok = True
        for iso, pth in human_ref_proteins.items():
            hhdr, hseq = read_single_fasta_with_header(Path(pth))
            qc = evaluate_protein(hseq, iso, iiib_ref, iiic_ref, args.pref_margin, args.min_segment_coverage)
            ok = (qc.protein_prefers == iso)
            human_ref_protein_ok = human_ref_protein_ok and ok
            debug_controls.append({
                "control_type": "human_refseq_protein_control",
                "species": "homo_sapiens",
                "role": iso,
                "selection_role": f"FGFR2_{iso}_human_reference_protein",
                "transcript_id": (manifest.get(iso).refseq_transcript if manifest.get(iso) else ""),
                "protein_id": (manifest.get(iso).refseq_protein if manifest.get(iso) else hhdr.split()[0]),
                "expected_isoform_from_event": iso,
                "expected_isoform_final": iso,
                "extracted_segment_start": str(qc.extracted_segment_start),
                "extracted_segment_end": str(qc.extracted_segment_end),
                "extracted_segment_length": str(qc.extracted_segment_length),
                "extracted_segment_sequence": qc.extracted_segment_sequence,
                "human_IIIb_reference_header": iiib_header,
                "human_IIIc_reference_header": iiic_header,
                "human_IIIb_reference_length": str(len(iiib_ref)),
                "human_IIIc_reference_length": str(len(iiic_ref)),
                "human_IIIb_identity": f"{qc.iiib_identity:.4f}",
                "human_IIIc_identity": f"{qc.iiic_identity:.4f}",
                "human_IIIb_coverage": f"{qc.iiib_coverage:.4f}",
                "human_IIIc_coverage": f"{qc.iiic_coverage:.4f}",
                "human_IIIb_marker_score": f"{qc.iiib_marker_score:.4f}",
                "human_IIIc_marker_score": f"{qc.iiic_marker_score:.4f}",
                "protein_prefers": qc.protein_prefers,
                "validation_status": "human_protein_control_passed" if ok else "human_protein_control_failed",
                "suspected_issue": "" if ok else "references_swapped_or_scoring_inverted",
            })
        control_status["human_refseq_protein_control"] = "pass" if human_ref_protein_ok else "fail"
    else:
        control_status["human_refseq_protein_control"] = "not_available"

    # (2) Human candidate control + (3) close-primate control.
    def candidate_control(control_type: str, species: str) -> str:
        present = False
        statuses = []
        for role in ("IIIb", "IIIc"):
            best = best_candidate(by_species_role.get((species, role), []))
            if not best:
                continue
            present = True
            prefers = best.get("protein_prefers")
            seq_available = best.get("protein_qc_status") not in ("protein_unavailable", "segment_unresolved")
            ok = (prefers == role)
            if not seq_available:
                outcome = "not_tested_protein_unavailable"
            elif ok:
                outcome = "pass"
            else:
                outcome = "fail"
            statuses.append(outcome)
            debug_controls.append({
                "control_type": control_type,
                "species": species,
                "role": role,
                "selection_role": best.get("selection_role", f"FGFR2_{role}_candidate"),
                "transcript_id": best.get("transcript_id", ""),
                "protein_id": best.get("protein_id", ""),
                "expected_isoform_from_event": best.get("expected_isoform_from_event", role),
                "expected_isoform_final": best.get("expected_isoform_final", role),
                "extracted_segment_start": best.get("extracted_segment_start", ""),
                "extracted_segment_end": best.get("extracted_segment_end", ""),
                "extracted_segment_length": best.get("extracted_segment_length", ""),
                "extracted_segment_sequence": best.get("extracted_segment_sequence", ""),
                "human_IIIb_reference_header": iiib_header,
                "human_IIIc_reference_header": iiic_header,
                "human_IIIb_reference_length": str(len(iiib_ref)),
                "human_IIIc_reference_length": str(len(iiic_ref)),
                "human_IIIb_identity": best.get("human_IIIb_identity", ""),
                "human_IIIc_identity": best.get("human_IIIc_identity", ""),
                "human_IIIb_coverage": best.get("human_IIIb_coverage", ""),
                "human_IIIc_coverage": best.get("human_IIIc_coverage", ""),
                "human_IIIb_marker_score": best.get("human_IIIb_marker_score", ""),
                "human_IIIc_marker_score": best.get("human_IIIc_marker_score", ""),
                "protein_prefers": prefers,
                "validation_status": best.get("validation_status", ""),
                "suspected_issue": best.get("suspected_issue", ""),
            })
        if not present:
            return "not_available"
        if any(s == "fail" for s in statuses):
            return "fail"
        if all(s == "pass" for s in statuses):
            return "pass"
        return "partial_or_not_tested"

    control_status["human_candidate_control"] = candidate_control("human_candidate", "homo_sapiens")
    primate_status = "not_available"
    for prim in ("pan_troglodytes", "gorilla_gorilla_gorilla", "gorilla_gorilla"):
        if any(sp == prim for (sp, _r) in by_species_role):
            primate_status = candidate_control("close_primate_candidate", prim)
            if primate_status != "not_available":
                control_status["close_primate_species"] = prim
                break
    control_status["close_primate_control"] = primate_status

    # --- Close-primate diagnostic resolution ------------------------------
    # The close-primate control can fail even when the human control passes.
    # Rather than failing or auto-swapping, diagnose WHY using event/exon
    # structure vs protein QC. Role stays event-based throughout.
    human_passed = (control_status.get("reference_self_control") == "pass"
                    and control_status.get("human_refseq_protein_control") != "fail")

    def diagnose_row(r: Dict[str, str], species_inverted: bool) -> Tuple[str, str, str]:
        method = r.get("segment_extraction_method", "")
        conf = r.get("segment_extraction_confidence", "")
        ev = r.get("event_structure_status", "")
        prefers = r.get("protein_prefers", "")
        expected = r.get("expected_isoform_final", "")
        if prefers == expected and prefers in ("IIIb", "IIIc"):
            consistency = "consistent"
        elif prefers in ("IIIb", "IIIc"):
            consistency = "inconsistent_protein_prefers_other"
        elif prefers == "ambiguous":
            consistency = "ambiguous_protein"
        else:
            consistency = "unresolved_protein"
        if method in ("fallback_protein_window", "unresolved") or conf in ("none",):
            diagnosis = "likely_segment_extraction_artifact"
            action = "Do not treat protein preference as decisive; needs resolved CDS->protein interval."
        elif ev == "ambiguous_exon_slot":
            diagnosis = "ambiguous_exon_slot_review"
            action = "Inspect exon slot (unclear/>2 alternative exons or weak mutual exclusivity)."
        elif consistency == "consistent":
            diagnosis = "control_passed"
            action = "None; event structure and protein QC agree."
        elif species_inverted and human_passed:
            diagnosis = "systematic_primate_inversion_review"
            action = ("Inspect exon-order direction rule (direction_validation provisional) and segment "
                      "extraction; do NOT auto-swap roles. Event/exon role kept as primary classifier.")
        else:
            diagnosis = "protein_event_conflict_review"
            action = "Keep exon/event role as primary; record protein QC conflict for manual review."
        return consistency, diagnosis, action

    primate_diag: List[Dict[str, str]] = []
    for sp in CLOSE_PRIMATE_SPECIES:
        sp_rows = [r for r in scored_candidates if r.get("species") == sp]
        if not sp_rows:
            continue
        sp_inverted = species_inversion.get(sp, False)
        dia_set = set()
        for r in sorted(sp_rows, key=lambda x: (x.get("role", ""), x.get("transcript_id", ""))):
            consistency, diagnosis, action = diagnose_row(r, sp_inverted)
            dia_set.add(diagnosis)
            primate_diag.append({
                "species": sp,
                "role": r.get("role", ""),
                "selection_role": r.get("selection_role", ""),
                "transcript_id": r.get("transcript_id", ""),
                "protein_id": r.get("protein_id", ""),
                "expected_isoform_from_event": r.get("expected_isoform_from_event", ""),
                "expected_isoform_final": r.get("expected_isoform_final", ""),
                "protein_prefers": r.get("protein_prefers", ""),
                "human_IIIb_identity": r.get("human_IIIb_identity", ""),
                "human_IIIc_identity": r.get("human_IIIc_identity", ""),
                "human_IIIb_coverage": r.get("human_IIIb_coverage", ""),
                "human_IIIc_coverage": r.get("human_IIIc_coverage", ""),
                "human_IIIb_marker_score": r.get("human_IIIb_marker_score", ""),
                "human_IIIc_marker_score": r.get("human_IIIc_marker_score", ""),
                "segment_extraction_method": r.get("segment_extraction_method", ""),
                "segment_extraction_confidence": r.get("segment_extraction_confidence", ""),
                "extracted_segment_start": r.get("extracted_segment_start", ""),
                "extracted_segment_end": r.get("extracted_segment_end", ""),
                "extracted_segment_length": r.get("extracted_segment_length", ""),
                "extracted_segment_sequence": r.get("extracted_segment_sequence", ""),
                "upstream_flanking_exon_id": r.get("upstream_flanking_exon_id", ""),
                "downstream_flanking_exon_id": r.get("downstream_flanking_exon_id", ""),
                "candidate_exon_slot_id": r.get("candidate_exon_slot_id", ""),
                "candidate_exon_length_nt": r.get("candidate_exon_length_nt", ""),
                "candidate_cds_length_nt": r.get("candidate_cds_length_nt", ""),
                "candidate_aa_length": r.get("candidate_aa_length", ""),
                "event_structure_status": r.get("event_structure_status", ""),
                "segment_vs_event_consistency": consistency,
                "diagnosis": diagnosis,
                "recommended_action": action,
            })
        # Species-level warnings derived from the diagnoses.
        if "systematic_primate_inversion_review" in dia_set:
            warnings.append({
                "species": sp, "warning_type": "close_primate_control_failed", "severity": "critical",
                "affected_roles": "IIIb;IIIc",
                "description": ("Close-primate IIIb and IIIc candidates are both inverted relative to the human "
                               "reference while the human control passes; exon-order direction is provisional."),
                "recommended_action": "Diagnose exon-order direction rule and segment extraction; do not auto-swap roles.",
            })
        if "protein_event_conflict_review" in dia_set:
            warnings.append({
                "species": sp, "warning_type": "protein_event_conflict", "severity": "warning",
                "affected_roles": "IIIb;IIIc",
                "description": "Protein QC prefers a different isoform than the exon/event assignment for at least one role.",
                "recommended_action": "Keep exon/event role as primary; treat protein QC as non-decisive review evidence.",
            })
        if "likely_segment_extraction_artifact" in dia_set:
            warnings.append({
                "species": sp, "warning_type": "likely_segment_extraction_artifact", "severity": "warning",
                "affected_roles": "IIIb;IIIc",
                "description": "Segment extraction is fallback/low confidence; protein preference may be an artifact.",
                "recommended_action": "Improve segment extraction (resolved CDS->protein interval) before trusting protein QC.",
            })
        if "ambiguous_exon_slot_review" in dia_set:
            warnings.append({
                "species": sp, "warning_type": "ambiguous_exon_slot", "severity": "warning",
                "affected_roles": "IIIb;IIIc",
                "description": "Exon slot structure is ambiguous (unclear mutual exclusivity / alt-exon count).",
                "recommended_action": "Inspect exon slot definition upstream before treating the event as decisive.",
            })

    # --- Build final selected_transcripts (role stays event-based) --------
    final_rows: List[Dict[str, str]] = []
    for sp, rows in selected_by_species.items():
        for r in rows:
            role = get_any(r, ["selection_role"])
            if role in {"FGFR2_IIIb_candidate", "FGFR2_IIIc_candidate",
                        "FGFR2_IIIb_provisional", "FGFR2_IIIc_provisional"}:
                continue
            rr = dict(r)
            for f in extra_fields:
                rr.setdefault(f, "not_applicable")
            rr["protein_validation_is_decisive"] = "false"
            rr.setdefault("primary_claim_eligible", "not_applicable")
            final_rows.append(rr)

        for role_label, isoform in [("FGFR2_IIIb_candidate", "IIIb"), ("FGFR2_IIIc_candidate", "IIIc")]:
            cand = best_candidate(by_species_role.get((sp, isoform), []))
            if cand:
                rr = dict(cand)
                rr["selection_role"] = role_label
                rr["selection_rank"] = "1"
                vstat = rr.get("validation_status", "")
                eligible = vstat in ("protein_validated_expected_isoform",
                                     "protein_supports_expected_isoform_below_strict_threshold")
                rr["selection_mode"] = ("protein_sequence_validated_isoform_candidate" if eligible
                                        else "exon_event_assigned_protein_qc_review_only")
                rr["primary_claim_eligible"] = "1" if eligible else "0"
                rr["overlapping_roles"] = "0"
                rr["all_roles_for_transcript"] = role_label
                rr["final_selection_reason"] = (
                    f"event-based role={isoform}; protein_prefers={rr.get('protein_prefers')}; "
                    f"validation_status={vstat}; IIIb(id={rr.get('human_IIIb_identity')},cov={rr.get('human_IIIb_coverage')}); "
                    f"IIIc(id={rr.get('human_IIIc_identity')},cov={rr.get('human_IIIc_coverage')}); "
                    f"protein QC is non-decisive for role assignment."
                )
                final_rows.append(rr)
            else:
                prev = [r for r in selected_by_species.get(sp, [])
                        if get_any(r, ["selection_role"]) == role_label]
                if prev and not args.drop_unvalidated_roles:
                    rr = dict(prev[0])
                    rr["selection_role"] = role_label
                    rr["selection_mode"] = "exon_supported_but_no_isoform_evidence_row_review_only"
                    rr["validation_status"] = "transcript_level_evidence_only_protein_unavailable"
                    rr["expected_isoform_from_event"] = isoform
                    rr["expected_isoform_final"] = isoform
                    rr["protein_validation_is_decisive"] = "false"
                    rr["primary_claim_eligible"] = "0"
                    rr["final_selection_reason"] = "Retained event-based role label for diagnostic export/mapping; no isoform-evidence candidate scored."
                    for f in extra_fields:
                        rr.setdefault(f, "")
                    final_rows.append(rr)

    roles_by_id: Dict[Tuple[str, str], List[str]] = defaultdict(list)
    for r in final_rows:
        roles_by_id[(get_any(r, ["species_canonical", "species_input"]), id_key(r))].append(get_any(r, ["selection_role"]))
    for r in final_rows:
        roles = sorted(set(roles_by_id[(get_any(r, ["species_canonical", "species_input"]), id_key(r))]))
        r["overlapping_roles"] = "1" if len(roles) > 1 else "0"
        r["all_roles_for_transcript"] = ";".join(roles)

    out_selected = args.output_selected or (outdir / "selected_transcripts.tsv")
    write_tsv(final_rows, out_selected, selected_fields)

    # --- Main validation table (PART F) -----------------------------------
    report_fields = [
        "species", "role", "selection_role", "transcript_id", "protein_id", "source_db",
        "expected_isoform_from_event", "expected_isoform_from_role", "expected_isoform_final",
        "protein_sequence_status", "protein_lookup_method", "protein_lookup_confidence",
        "protein_length_aa", "protein_length_aa_observed",
        "segment_extraction_method", "segment_extraction_confidence",
        "extracted_segment_start", "extracted_segment_end", "extracted_segment_length",
        "human_IIIb_identity", "human_IIIc_identity", "human_IIIb_coverage", "human_IIIc_coverage",
        "human_IIIb_marker_score", "human_IIIc_marker_score",
        "protein_prefers", "protein_qc_status", "validation_status", "suspected_issue",
        "validation_warning", "protein_validation_is_decisive",
        # legacy / diagnostic columns
        "human_IIIb_similarity_legacy_unbounded", "human_IIIc_similarity_legacy_unbounded",
        "species_canonical", "species_input", "internal_transcript_id", "transcript_name",
        "translation_id_source", "iii_isoform_assignment", "iii_isoform_confidence",
        "extracted_segment_sequence", "score", "protein_sequence_source", "protein_sequence_detail",
    ]
    scored_candidates.sort(key=lambda r: (
        str(r.get("species", r.get("species_canonical", ""))),
        str(r.get("role", "")),
        str(r.get("transcript_id", clean_id(get_any(r, ["transcript_id_source"])))),
    ))
    write_tsv(scored_candidates, outdir / "fgfr2_III_candidate_protein_validation.tsv", report_fields)

    # Warnings table (PART E schema).
    write_tsv(warnings, outdir / "fgfr2_III_candidate_protein_validation_warnings.tsv",
              ["species", "warning_type", "severity", "affected_roles", "description", "recommended_action"])

    # Debug controls table (PART B schema).
    debug_fields = [
        "control_type", "species", "role", "selection_role", "transcript_id", "protein_id",
        "expected_isoform_from_event", "expected_isoform_final",
        "extracted_segment_start", "extracted_segment_end", "extracted_segment_length", "extracted_segment_sequence",
        "human_IIIb_reference_header", "human_IIIc_reference_header",
        "human_IIIb_reference_length", "human_IIIc_reference_length",
        "human_IIIb_identity", "human_IIIc_identity", "human_IIIb_coverage", "human_IIIc_coverage",
        "human_IIIb_marker_score", "human_IIIc_marker_score",
        "protein_prefers", "validation_status", "suspected_issue",
    ]
    write_tsv(debug_controls, outdir / "fgfr2_III_candidate_protein_validation_debug_controls.tsv", debug_fields)

    # Close-primate diagnostic table (PART: diagnostic resolution).
    primate_diag_fields = [
        "species", "role", "selection_role", "transcript_id", "protein_id",
        "expected_isoform_from_event", "expected_isoform_final", "protein_prefers",
        "human_IIIb_identity", "human_IIIc_identity", "human_IIIb_coverage", "human_IIIc_coverage",
        "human_IIIb_marker_score", "human_IIIc_marker_score",
        "segment_extraction_method", "segment_extraction_confidence",
        "extracted_segment_start", "extracted_segment_end", "extracted_segment_length", "extracted_segment_sequence",
        "upstream_flanking_exon_id", "downstream_flanking_exon_id", "candidate_exon_slot_id",
        "candidate_exon_length_nt", "candidate_cds_length_nt", "candidate_aa_length",
        "event_structure_status", "segment_vs_event_consistency", "diagnosis", "recommended_action",
    ]
    write_tsv(primate_diag, outdir / "fgfr2_III_close_primate_control_diagnostics.tsv", primate_diag_fields)

    # Summary table with counts.
    summary_rows: List[Dict[str, str]] = []
    for group, col in [
        ("source_db", "source_db"),
        ("protein_sequence_status", "protein_sequence_status"),
        ("validation_status", "validation_status"),
        ("protein_prefers", "protein_prefers"),
        ("suspected_issue", "suspected_issue"),
        ("segment_extraction_method", "segment_extraction_method"),
        ("expected_isoform_final", "expected_isoform_final"),
    ]:
        for k, v in sorted(Counter(str(r.get(col, "")) for r in scored_candidates).items()):
            summary_rows.append({"group": group, "key": k, "subkey": "", "count": str(v)})
    write_tsv(summary_rows, outdir / "fgfr2_III_candidate_protein_validation_summary.tsv",
              ["group", "key", "subkey", "count"])

    # Final selected protein validation summary (one row per species-role).
    final_summary: List[Dict[str, str]] = []
    for r in final_rows:
        role = get_any(r, ["selection_role"])
        if role not in {"FGFR2_IIIb_candidate", "FGFR2_IIIc_candidate"}:
            continue
        final_summary.append({
            "species": get_any(r, ["species_canonical", "species_input"]),
            "selection_role": role,
            "expected_isoform_final": r.get("expected_isoform_final", ""),
            "transcript_id": r.get("transcript_id", clean_id(get_any(r, ["transcript_id_source"]))),
            "protein_id": r.get("protein_id", ""),
            "protein_prefers": r.get("protein_prefers", ""),
            "human_IIIb_identity": r.get("human_IIIb_identity", ""),
            "human_IIIc_identity": r.get("human_IIIc_identity", ""),
            "human_IIIb_coverage": r.get("human_IIIb_coverage", ""),
            "human_IIIc_coverage": r.get("human_IIIc_coverage", ""),
            "validation_status": r.get("validation_status", ""),
            "suspected_issue": r.get("suspected_issue", ""),
            "primary_claim_eligible": r.get("primary_claim_eligible", ""),
            "protein_validation_is_decisive": "false",
        })
    final_summary.sort(key=lambda r: (r["species"], r["selection_role"]))
    write_tsv(final_summary, outdir / "fgfr2_III_final_selected_protein_validation_summary.tsv",
              ["species", "selection_role", "expected_isoform_final", "transcript_id", "protein_id",
               "protein_prefers", "human_IIIb_identity", "human_IIIc_identity",
               "human_IIIb_coverage", "human_IIIc_coverage", "validation_status",
               "suspected_issue", "primary_claim_eligible", "protein_validation_is_decisive"])

    # --- Counts + metadata ------------------------------------------------
    by_seqstat = Counter(str(r.get("protein_sequence_status", "")) for r in scored_candidates)
    by_valstat = Counter(str(r.get("validation_status", "")) for r in scored_candidates)
    by_prefers = Counter(str(r.get("protein_prefers", "")) for r in scored_candidates)
    by_suspected = Counter(str(r.get("suspected_issue", "")) for r in scored_candidates)
    inversion_species = sorted([sp for sp, inv in species_inversion.items() if inv])

    # Human positive-control gate.
    human_control = control_status.get("human_candidate_control", "not_available")
    human_ref_protein_control = control_status.get("human_refseq_protein_control", "not_available")
    reference_control = control_status.get("reference_self_control", "fail")
    if reference_control != "pass":
        human_status = "reference_control_failed"
    elif human_ref_protein_control == "fail":
        human_status = "fail_human_reference_protein_inverted"
    elif human_control == "fail":
        human_status = "fail_human_candidate_inverted"
    elif human_ref_protein_control == "pass":
        human_status = "pass_human_reference_protein_prefers_matching_isoform"
    elif human_control == "pass":
        human_status = "pass_human_IIIb_and_IIIc_prefer_matching_reference"
    else:
        human_status = f"human_candidate_{human_control}"

    md = [
        "# FGFR2 protein-aware IIIb/IIIc candidate QC report",
        "",
        f"Generated by `{SCRIPT_NAME}` version `{SCRIPT_VERSION}`.",
        "",
        "## Method",
        "",
        "The IIIb/IIIc role is assigned from exon/event architecture (Step 4). Protein "
        "comparison is QC only and never changes the role. Each candidate protein is locally "
        "aligned to the curated human IIIb and IIIc cassette segments; bounded identity and "
        "coverage decide which isoform the protein prefers. Systematic inversions are flagged "
        "for review and never auto-swapped.",
        "",
        "## Controls",
        "",
        f"- reference self-control: `{reference_control}`",
        f"- human candidate control: `{human_control}`",
        f"- close-primate control: `{primate_status}` (species: `{control_status.get('close_primate_species','n/a')}`)",
        f"- reference manifest check: `{manifest_status}`",
        "",
        f"## Human positive-control status: `{human_status}`",
        "",
        "## Validation status counts",
        "",
    ]
    for k, v in sorted(by_valstat.items()):
        md.append(f"- `{k}`: {v}")
    md += ["", "## Species flagged with systematic isoform inversion", ""]
    md += [f"- `{sp}`" for sp in inversion_species] or ["- none"]
    md += ["", "## Close-primate control diagnostics", ""]
    if primate_diag:
        for sp in sorted({d["species"] for d in primate_diag}):
            dia = Counter(d["diagnosis"] for d in primate_diag if d["species"] == sp)
            md.append(f"- `{sp}`: " + ", ".join(f"{k}={v}" for k, v in sorted(dia.items())))
    else:
        md.append("- no close-primate species present")
    (outdir / "fgfr2_III_candidate_protein_validation_report.md").write_text("\n".join(md) + "\n", encoding="utf-8")

    metadata = {
        "script_name": SCRIPT_NAME,
        "script_version": SCRIPT_VERSION,
        "run_datetime_utc": datetime.now(timezone.utc).isoformat(),
        "parameters": {
            "min_identity": args.min_identity, "min_coverage": args.min_coverage,
            "pref_margin": args.pref_margin, "min_segment_coverage": args.min_segment_coverage,
            "drop_unvalidated_roles": args.drop_unvalidated_roles,
        },
        "row_counts": {"selected_in": len(selected), "candidate_rows_scored": len(scored_candidates),
                       "selected_out": len(final_rows), "warnings": len(warnings)},
        "controls": control_status,
        "reference_manifest_status": manifest_status,
        "protein_sequence_status_counts": dict(by_seqstat),
        "validation_status_counts": dict(by_valstat),
        "protein_prefers_counts": dict(by_prefers),
        "suspected_issue_counts": dict(by_suspected),
        "systematic_inversion_species": inversion_species,
        "close_primate_diagnoses": {
            sp: dict(Counter(d["diagnosis"] for d in primate_diag if d["species"] == sp))
            for sp in sorted({d["species"] for d in primate_diag})
        },
        "cache_index_composition": cache_index.composition(),
        "human_status": human_status,
    }
    (outdir / "run_metadata.json").write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")

    # --- Hard stop conditions ---------------------------------------------
    if reference_control != "pass":
        raise SystemExit(
            "[FAIL] reference_control_failed: human IIIb/IIIc reference segments do not prefer "
            "themselves. References may be swapped or scoring inverted. See "
            f"{outdir / 'fgfr2_III_candidate_protein_validation_debug_controls.tsv'}")
    if human_ref_protein_control == "fail":
        raise SystemExit(
            "[FAIL] human positive control failed: the human full-length FGFR2-IIIb/IIIc proteins "
            "do not prefer their matching reference. References swapped or scoring inverted. See "
            f"{outdir / 'fgfr2_III_candidate_protein_validation_debug_controls.tsv'}")
    if manifest_status == "fail" and args.strict_manifest:
        raise SystemExit(
            f"[FAIL] reference manifest check failed. See {outdir / 'fgfr2_III_reference_manifest_check.tsv'}")
    if args.strict and human_status.startswith("fail"):
        raise SystemExit(f"[FAIL] {human_status}. See {outdir / 'fgfr2_III_candidate_protein_validation_debug_controls.tsv'}")
    return metadata


def build_arg_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="Protein-aware QC of FGFR2 IIIb/IIIc candidate transcripts (role stays event-based).")
    ap.add_argument("--selected", required=True, type=Path, help="Step 5 selected_transcripts.tsv")
    ap.add_argument("--transcripts", required=True, type=Path, help="Step 2 transcripts.tsv")
    ap.add_argument("--isoform_evidence", required=True, type=Path, help="Step 4 fgfr2_isoform_evidence.tsv")
    ap.add_argument("--human_iiib_segment_fasta", required=True, type=Path)
    ap.add_argument("--human_iiic_segment_fasta", required=True, type=Path)
    ap.add_argument("--reference_manifest", type=Path, default=None,
                    help="reference/fgfr2_human_iiib_iiic_manifest.tsv")
    ap.add_argument("--human_iiib_protein_fasta", type=Path, default=None,
                    help="Human full-length FGFR2-IIIb protein for the mandatory offline positive control")
    ap.add_argument("--human_iiic_protein_fasta", type=Path, default=None,
                    help="Human full-length FGFR2-IIIc protein for the mandatory offline positive control")
    ap.add_argument("--cache", type=Path, default=None, help="Optional NCBI datasets cache for local protein FASTA lookup")
    ap.add_argument("--outdir", required=True, type=Path)
    ap.add_argument("--output_selected", type=Path, default=None)
    ap.add_argument("--min_identity", type=float, default=0.70, help="Strict identity threshold for protein_validated")
    ap.add_argument("--min_coverage", type=float, default=0.70, help="Strict reference coverage threshold for protein_validated")
    ap.add_argument("--pref_margin", type=float, default=0.05, help="Min identity*coverage margin to call a preference")
    ap.add_argument("--min_segment_coverage", type=float, default=0.30, help="Min reference coverage to extract a segment")
    ap.add_argument("--include_low_confidence", action="store_true")
    ap.add_argument("--drop_unvalidated_roles", action="store_true", help="Do not retain unvalidated previous III roles as QC rows")
    ap.add_argument("--strict", action="store_true", help="Fail if human candidate control inverts")
    ap.add_argument("--strict_manifest", action="store_true", help="Fail if reference manifest check fails")
    ap.add_argument("--no_ensembl_rest", action="store_true")
    ap.add_argument("--ensembl_retries", type=int, default=3)
    ap.add_argument("--ensembl_sleep", type=float, default=0.4)
    ap.add_argument("--ensembl_timeout", type=int, default=30)
    return ap


def main() -> None:
    args = build_arg_parser().parse_args()
    md = run(args)
    print(f"[OK] candidate rows scored: {md['row_counts']['candidate_rows_scored']}")
    print(f"[OK] selected rows out: {md['row_counts']['selected_out']}")
    print(f"[OK] warnings: {md['row_counts']['warnings']}")
    print(f"[OK] controls: {md['controls']}")
    print(f"[OK] human status: {md['human_status']}")
    print(f"[OK] systematic inversion species: {md['systematic_inversion_species']}")
    print(f"[OK] close-primate diagnoses: {md['close_primate_diagnoses']}")
    print(f"[OK] output directory: {args.outdir}")


if __name__ == "__main__":
    main()
